
# tap repositories and their packages

tap homebrew/core
brew cask
brew clang-format
brew coreutils
brew emacs
brew exiftool
brew ffmpeg
brew gcc
brew git-ftp
brew gnupg
brew gnuplot
brew jq
brew mas
brew mysql
brew nano
brew nodebrew
brew openjdk
brew progress
brew pypy3
brew telnet
brew thefuck
brew tree
brew watch
brew watchman
brew wget
brew xpdf
brew yarn

tap homebrew/cask-versions

tap homebrew/services

tap homebrew/cask
cask adobe-acrobat-reader
cask android-file-transfer
cask atok
cask basictex
cask cyberduck
cask docker
cask emacs
cask google-chrome
cask iina
cask karabiner-elements
cask ngrok
cask skype
cask sourcetree
cask typora
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask java
cask zoomus

# App Store applications
appstore 411643860 DaisyDisk (4.12.1)
appstore 1186187538 Ethernet Status (3.4)
appstore 409183694 Keynote (10.3.8)
appstore 441258766 Magnet (2.5.0)
appstore 409203825 Numbers (10.3.5)
appstore 409201541 Pages (10.3.5)
appstore 1289119450 SafariMarkdownLinker (1.0)
appstore 803453959 Slack (4.11.3)
appstore 1482490089 Tampermonkey (4.11.6117)
appstore 1538509686 VisBug (0.3.0)
appstore 414855915 WinArchiver Lite (2.5.3)
appstore 497799835 Xcode (12.2)

# Additional files
file ~/.brewfile/.Brewfile
