
# tap repositories and their packages

tap homebrew/core
brew cask
brew clang-format
brew coreutils
brew emacs, link: true
brew exiftool
brew ffmpeg
brew gcc
brew git-ftp
brew gnupg
brew gnuplot
brew jq
brew mas
brew mysql
brew nano
brew nodebrew
brew openssl@1.1
brew progress
brew pypy3
brew telnet
brew watchman
brew wget
brew xpdf
brew yarn


tap homebrew/cask
cask adobe-acrobat-reader
cask android-file-transfer
cask basictex
cask cyberduck
cask docker
cask emacs
cask google-chrome
cask iina
cask java
cask karabiner-elements
cask ngrok
cask skype
cask sourcetree
cask typora
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 411643860 DaisyDisk (4.10)
appstore 409183694 Keynote (10.1)
appstore 441258766 Magnet (2.4.6)
appstore 409203825 Numbers (10.1)
appstore 409201541 Pages (10.1)
appstore 1289119450 SafariMarkdownLinker (1.0)
appstore 803453959 Slack (4.8.0)
appstore 1482490089 Tampermonkey (4.11.6117)
appstore 497799835 Xcode (11.6)

# Additional files
file ./.Brewfile
