
# tap repositories and their packages

tap homebrew/core
brew cask
brew clang-format
brew coreutils
brew emacs, link: true
brew exiftool
brew ffmpeg
brew gcc
brew git-ftp
brew gnupg
brew gnuplot
brew jq
brew mas
brew mysql
brew nano
brew nodebrew
brew progress
brew pypy3
brew telnet
brew tree
brew watch
brew watchman
brew wget
brew xpdf
brew yarn

tap homebrew/services

tap homebrew/cask
cask adobe-acrobat-reader
cask android-file-transfer
cask basictex
cask cyberduck
cask docker
cask emacs
cask google-chrome
cask java
cask karabiner-elements
cask skype
cask sourcetree
cask typora
cask visual-studio-code
cask zoomus

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836 GarageBand (10.3.4)
appstore 408981434 iMovie (10.1.14)
appstore 409183694 Keynote (10.1)
appstore 441258766 Magnet (2.4.5)
appstore 409203825 Numbers (10.1)
appstore 409201541 Pages (10.1)
appstore 844918735 PicGIF Lite (2.0.8)
appstore 1289119450 SafariMarkdownLinker (1.0)
appstore 803453959 Slack (4.7.0)
appstore 1482490089 Tampermonkey (4.10.6108)
appstore 497799835 Xcode (11.5)

# Additional files
file ./${HOST}.Brewfile
